tileshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

tileshop/orders/urls.py
from django.urls import path

from orders.views import order_create

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create')
]

tileshop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('category/<slug:category_slug>',
         views.category_list, name='category'),
    path('products/<slug:product_slug>/',
         views.product_detail, name='product'),
    path('create_review/<int:product_id>',
         views.create_review, name='create_review'),
    path('', views.index, name='index'),
]

tileshop/tileshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tileshop/cart/forms.py
from django import forms

from tileshop.constans import CartLimit, CartValidate


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(
        initial=CartLimit.QUANTITY_INITIAL.value,
        min_value=CartValidate.QUANTITY_MIN_VALUE.value,
        max_value=CartValidate.QUANTITY_MAX_VALUE.value,
        label='Кол'
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

tileshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from cart.cart import Cart
from cart.forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True}
        )
    return render(request, 'cart/detail.html', {'cart': cart})

tileshop/templates/cart/detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
	{{ title }}
{% endblock %}
{% block content %}
	<section class="h-100 h-custom" style="background-color: #d4d2d2;">
		<div class="container py-5 h-100">
			<div class="row d-flex justify-content-center align-items-center h-100">
				<div class="col">
					<div class="card">
						<div class="card-body p-4">

							<div class="row">

								<div class="col-lg-7">
									<h5 class="mb-3"><a href="{% url "shop:index" %}"
									                    class="text-body"><i
											class="fas fa-long-arrow-alt-left me-2"></i>Продолжить
										покупки</a></h5>
									<hr>
									<div
											class="d-flex justify-content-between align-items-center mb-4">
										<div>
											<p class="mb-1">Корзина</p>
											<div class="cart">
												{% with total_items=cart|length %}
													{% if cart|length > 0 %}
														Ваша корзина:
														<a href="{% url "cart:cart_detail" %}">
															{{ total_items }} item{{ total_items|pluralize }}
														</a>
													{% else %}
														Ваша корзина пуста.
													{% endif %}
												{% endwith %}
											</div>
										</div>
									</div>
									{% for item in cart %}
										{% with product=item.poduct %}
											<div class="card mb-3">
												<div class="card-body">
													<div class="d-flex justify-content-between">
														<div class="d-flex flex-row align-items-center">
															{% thumbnail item.product.images "75x75" crop="center" upscale=True as im %}
																<a href="{{ item.product.get_absolute_url }}">
																	<img class="card-img my-2 bg-white"
																	     src="{{ im.url }}" alt="">
																</a>
															{% endthumbnail %}
															<div class="ms-3">
																<h5>{{ item.product.name }}</h5>
															</div>
														</div>
														<div class="d-flex flex-row align-items-center">
															<div style="width: 50px;">
																<h5 class="fw-normal mb-0">{{ item.quantity }}</h5>
															</div>
															<div style="width: 120px;">
																<h5 class="mb-0">{{ item.product.price }}р.</h5>
															</div>
															<div style="width: 80px;">
																<a href="{% url "cart:cart_remove" item.product.id %}">del</a>
															</div>
															<a href="#!" style="color: #cecece;"><i
																	class="fas fa-trash-alt"></i></a>
														</div>
													</div>
												</div>
											</div>
										{% endwith %}
									{% endfor %}
								</div>
								<a href="{% url "orders:order_create" %}" class="button">
									<button class="btn btn-success " data-toggle="button">Оформить</button>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}