tileshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

tileshop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('category/<slug:category_slug>',
         views.category_list, name='category'),
    path('products/<slug:product_slug>/',
         views.product_detail, name='product'),
    path('create_review/<int:product_id>',
         views.create_review, name='create_review'),
    path('', views.index, name='index'),
]

tileshop/tileshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tileshop/shop/models.py
from django.contrib.auth import get_user_model
from django.db import models

from django.urls import reverse

from tileshop.constans import CategoryLimit, SubCategoryLimit, ProductLimit

User = get_user_model()


class Category(models.Model):
    title = models.CharField(
        max_length=CategoryLimit.MAX_LEN_TITLE.value,
        verbose_name='Категория'
    )
    slug = models.SlugField(
        unique=True,
        db_index=True,
        verbose_name='URL'
    )
    images = models.ImageField(
        upload_to='image/categories/',
        verbose_name='Фото категории'
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:category', kwargs={'category_slug': self.slug})

    class Meta:
        ordering = ('id',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class SubCategory(models.Model):
    title = models.CharField(
        max_length=SubCategoryLimit.MAX_LEN_TITLE.value,
        verbose_name='Подкатегория'
    )
    slug = models.SlugField(
        unique=True,
        db_index=True,
        verbose_name='URL'
    )
    images = models.ImageField(
        upload_to='image/subcategories/',
        verbose_name='Фото подкатегории'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='subcategory',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'


class Product(models.Model):
    name = models.CharField(
        max_length=ProductLimit.MAX_LEN_NAME.value,
        verbose_name='Наименование товара'
    )
    stripe_id = models.CharField()
    slug = models.SlugField(
        unique=True,
        db_index=True,
        verbose_name='URL'
    )
    description = models.TextField(
        verbose_name='Описание'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата добавления товара'
    )
    images = models.ImageField(
        upload_to='image/products/',
        verbose_name='Фото товара'
    )
    create_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата поступления'
    )
    price = models.DecimalField(
        max_digits=ProductLimit.MAX_DIG_PRICE.value,
        decimal_places=ProductLimit.DECIMAL_PLACES.value,
        verbose_name='Цена'
    )
    available = models.BooleanField(
        default=True,
        verbose_name='Товар в наличии'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='products'
    )
    stock = models.PositiveIntegerField(
        default=ProductLimit.DEFAULT_STOCK.value,
        verbose_name='Количество'
    )
    subcategory = models.ForeignKey(
        SubCategory,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='products',
        verbose_name='Подкатегория'
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product', kwargs={'product_slug': self.slug})

    def get_return_price(self):
        return f'{self.price}'

    class Meta:
        ordering = ('name',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Review(models.Model):
    product = models.ForeignKey(
        Product,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='review'
    )
    text = models.TextField(
        verbose_name='Текст',
        help_text='Напишите отзыв'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='review',
        verbose_name='Автор'
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

tileshop/shop/forms.py
from django import forms

from shop.models import Review


class ReviewCreateForm(forms.ModelForm):
    text = forms.CharField(label='',
                           widget=forms.Textarea(
                               attrs={'class': 'form-control'}))

    class Meta:
        model = Review
        fields = ('text',)

tileshop/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect

from cart.forms import CartAddProductForm
from shop.forms import ReviewCreateForm
from shop.models import Category, Product


def index(request):
    categories = Category.objects.select_related()
    template = 'shop/index.html'
    context = {
        'title': 'Магазин',
        'categories': categories
    }
    return render(request, template, context)


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    subcategory = category.subcategory.select_related()
    cart_product_form = CartAddProductForm()
    if not subcategory:
        products = category.products.select_related()
        template = 'shop/category_list.html'
        context = {
            'title': category.slug,
            'products': products,
            'cart_product_form': cart_product_form,
        }
        return render(request, template, context)
    subcategory = category.subcategory.select_related()
    template = 'shop/index.html'
    context = {
        'title': 'Магазин',
        'categories': subcategory,
    }
    return render(request, template, context)


def product_detail(request, product_slug):
    product = get_object_or_404(Product,
                                slug=product_slug,
                                available=True)

    cart_product_form = CartAddProductForm()
    create_review_form = ReviewCreateForm()
    templates = 'shop/product_detail.html'
    context = {
        'title': product.name,
        'product': product,
        'cart_product_form': cart_product_form,
        'create_review_form': create_review_form,
    }
    return render(request, templates, context)


def create_review(request, product_id):
    template = 'shop/product_detail.html'
    product = get_object_or_404(Product, id=product_id)
    create_review_form = ReviewCreateForm(request.POST or None)
    if create_review_form.is_valid():
        review = create_review_form.save(commit=False)
        review.author = request.user
        review.product = product
        review.save()
        return redirect('shop:product', product.slug)
    context = {
        'product': product,
    }
    return render(request, template, context)

tileshop/templates/shop/category_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load ratings %}
{% block title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container pt-8">
		<div class="row">
			{% for product in products %}
				<div class="col-lg-4 col-md-6 col-sm-12 p-3">
					<div class="card text-center shadow p-3 mb-5 bg-white rounded">
						<a href="{{ product.get_absolute_url }}">
							{% thumbnail product.images "350x350" crop="center" upscale=True as im %}
								<img class="card-img my-2 bg-white" src="{{ im.url }}" alt="">
							{% endthumbnail %}
						</a>
						<h6>{{ product.name }}</h6>
							{% ratings product icon_height=15 icon_width=15 %}
						<h5>{{ product.price }} р.</h5>
						<form action="{% url "cart:cart_add" product.id %}" method="post">
							{% csrf_token %}
							{{ cart_product_form }}
							<button class="btn btn-success " data-toggle="button">В корзину
							</button>
						</form>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

tileshop/templates/shop/category_product.html
{% extends '../base.html' %}
{% load thumbnail %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="container pt-4" >
        <div class="row">
            {% for product in products %}
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="card text-center shadow p-3 mb-5 bg-white rounded">
{#                        <a href="{% url 'shop:category_products' category.slug %}">#}
                        {% thumbnail product.images "350x350" crop="center" as im %}
                            <img class="card-img my-2 bg-white" src="{{ im.url }}" alt="">
                        {% endthumbnail %}
{#                        </a>#}
                        <h6>{{ product.name }}</h6>
                        <hr>
                        <p>{{ product.description|truncatewords:15 }}</p>
                        <h5>{{ product.price }} р.</h5>
                        <button type="button" class="btn btn-success " data-toggle="button" aria-pressed="false" style="display: block; margin-left: auto;">В карзину</button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

tileshop/templates/shop/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="container pt-4" >
        <div class="row">
            {% for category in categories %}
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="card text-center shadow p-3 mb-5 bg-white rounded">
                        <a href="{{ category.get_absolute_url }}">
                        {% thumbnail category.images "350x350" crop="center" as im %}
                            <img class="card-img my-2" src="{{ im.url }}" alt="">
                        {% endthumbnail %}
                        </a>
                        <h6>{{ category.title }}</h6>
                    </div>
                    <br>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

tileshop/templates/shop/product_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
	{{ title }}
{% endblock %}
{% block content %}
	<section class="h-100 h-custom p-4" style="background-color: #d9d9d9;">
		<div class="row d-flex justify-content-center align-items-center h-100">
			<div class="col">
				<div class="container pt-8 h-100">
					<div class="card">
						<div class="card shadow p-4 bg-white rounded">
							<div class="row align-items-center">
								<div class="col-lg-6">
									{% thumbnail product.images "350x350" crop="center" upscale=True as im %}
										<img class="card-img my-2 bg-white" src="{{ im.url }}"
										     alt="">
									{% endthumbnail %}
								</div>
								<div class="col-lg-6">
									<h1>{{ product.name }}</h1>
									<hr>
									<p>{{ product.description }}</p>

									<h5>{{ product.price }} р.</h5>
									<form action="{% url "cart:cart_add" product.id %}"
									      method="post">
										{% csrf_token %}
										{{ cart_product_form }}
										<button class="btn btn-success " data-toggle="button">
											В корзину
										</button>
									</form>
								</div>
							</div>
						<div class="card">
									<div class="card-header">
										Оставьте отзыв
									</div>
									<div class="card-body">
										<form action="{% url 'shop:create_review' product.id %}"
										method="post">
											{% csrf_token %}
											{{ create_review_form.as_p }}
											<button type="submit" class="btn btn-primary">
												Отправить
											</button>
										</form>
									</div>
								</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		</div>
	</section>
{% endblock %}

tileshop/templates/shop/reviews.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
    {{ body }}
{% endblock %}

tileshop/templates/shop/rewies.html
{% extends '../base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
    {{ body }}
{% endblock %}