tileshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

tileshop/payment/urls.py
from django.urls import path

from payment.views import (CreateCheckoutSession,
                           SuccessView,
                           CancelView)

app_name = 'payment'

urlpatterns = [
    path('success/', SuccessView.as_view(), name='success'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('create-checkout-session/', CreateCheckoutSession.as_view(),
         name='create-checkout-session'),

]

tileshop/tileshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tileshop/payment/views.py
from http import HTTPStatus

from django.shortcuts import redirect
from django.views import View
from django.views.generic import TemplateView
from django.conf import settings
import stripe

from shop.models import Product
from cart.cart import Cart

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessView(TemplateView):
    template_name = 'payment/success.html'


class CancelView(TemplateView):
    template_name = 'payment/cancel.html'


class CreateCheckoutSession(View):
    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        *product_ids, = cart.cart
        products = Product.objects.filter(id__in=product_ids)
        line_items = []
        for product in products:
            line_items.append({
                'price': product.stripe_id,
                'quantity': cart.cart[str(product.id)]['quantity'],
            })
        domain = 'http://localhost:8000/payment'
        try:
            checkout_session = stripe.checkout.Session.create(
                line_items=line_items,
                mode='payment',
                success_url=domain + '/success/',
                cancel_url=domain + '/cancel/',
            )
        except Exception as e:
            return str(e)
        return redirect(checkout_session.url, code=HTTPStatus.SEE_OTHER)

tileshop/templates/payment/cancel.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

tileshop/templates/payment/checkpayment.html
<!DOCTYPE html>
<html>
	<head>
		<title>Buy cool new product</title>
{#		<link rel="stylesheet" href="style.css">#}
		<script src="https://js.stripe.com/v3/"></script>
	</head>
	<body>
		<section>
			<div class="product">
{#				<img src="https://i.imgur.com/EHyR2nP.png"#}
{#				     alt="The cover of Stubborn Attachments"/>#}
				<div class="description">
					<h3>{{ product.name }}</h3>
					<h5>{{ product.price }}</h5>
				</div>
			</div>
			<form action="{% url "payment:create-checkout-session" product.id %}" method="POST">
				<button type="submit" id="checkout-button">Checkout</button>
				{% csrf_token %}
			</form>
		</section>
	</body>
</html>

tileshop/templates/payment/success.html
<!DOCTYPE html>
<html>
<head>
  <title>Thanks for your order!</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>
      We appreciate your business! If you have any questions, please email
      <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>
  </section>
</body>
</html>